# Generated by Django 3.0.6 on 2020-05-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productcode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('color1', models.CharField(blank=True, max_length=10)),
                ('color2', models.CharField(blank=True, max_length=10)),
                ('color3', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
