# Generated by Django 3.0.6 on 2020-05-21 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productcode',
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.ImageField(upload_to='product/image')),
                ('color1', models.ImageField(blank=True, upload_to='product/image')),
                ('color2', models.ImageField(blank=True, upload_to='product/image')),
                ('color3', models.ImageField(blank=True, upload_to='product/image')),
                ('back', models.ImageField(upload_to='product/image')),
                ('chart', models.ImageField(upload_to='product/image')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
