# Generated by Django 3.0.6 on 2020-05-29 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200529_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 10, 48, 0, 934759)),
        ),
    ]
