# Generated by Django 3.0.6 on 2020-08-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200529_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='title',
            new_name='product',
        ),
    ]
