# Generated by Django 3.0.6 on 2020-08-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200822_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product',
            new_name='title',
        ),
    ]
