# Generated by Django 3.0.6 on 2020-08-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200823_0811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color1',
            new_name='color',
        ),
    ]
