# Generated by Django 3.0.6 on 2020-05-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200530_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='orderid',
            name='order_status',
            field=models.CharField(default='Initiated', max_length=100),
        ),
        migrations.AddField(
            model_name='orderid',
            name='payment_status',
            field=models.CharField(default='Initiated', max_length=100),
        ),
    ]
