# Generated by Django 3.0.6 on 2020-06-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200530_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderid',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
