# Generated by Django 3.0.6 on 2020-08-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200606_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
