# Generated by Django 3.0.6 on 2020-08-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200823_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetail',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
